name: 'env'
description: 'Share variables between spaceporn dependencies workflows'
runs:
  using: "composite"
  steps:
    - name: Install yq on Windows
      if: runner.os == 'Windows'
      id: install
      shell: bash
      run: |
        if choco install yq || scoop install main/yq || winget install --id MikeFarah.yq
        then
          printf 'succeed=true\n' >> "${GITHUB_OUTPUT}"
        else
          printf 'succeed=false\n' >> "${GITHUB_OUTPUT}"
        fi

    - if: runner.os == 'Windows' && steps.install.outputs.succeed != 'true'
      uses: actions/setup-go@v5

    - name: Install yq with GO on Windows
      if: runner.os == 'Windows' && steps.install.outputs.succeed != 'true'
      shell: bash
      run: |
        go install github.com/mikefarah/yq/v4@latest

    - name: Load environment
      env:
        FILTER: '. | to_entries | map([.key, .value] | join ("=")) | .[]'
      shell: bash
      run: |
        yq "${FILTER}" "${GITHUB_ACTION_PATH}/env.yml" >> "${GITHUB_ENV}"
