name: 'env'
description: 'Share variables between spaceporn dependencies workflows'
inputs:
  repository:
    description: 'The repository name'
    required: false
    default: "${{ github.action_repository }}"
  path:
    description: 'The env.yml path'
    required: false
    default: "${{ github.action_path }}"
runs:
  using: "composite"
  steps:
    - name: Install yq on Windows
      if: runner.os == 'Windows'
      id: install
      shell: bash
      run: |
        if choco install yq || scoop install main/yq || winget install --id MikeFarah.yq
        then
          printf 'succeed=true\n' >> "${GITHUB_OUTPUT}"
        else
          printf 'succeed=false\n' >> "${GITHUB_OUTPUT}"
        fi

    - if: runner.os == 'Windows' && steps.install.outputs.succeed != 'true'
      uses: actions/setup-go@v5

    - name: Install yq with GO on Windows
      if: runner.os == 'Windows' && steps.install.outputs.succeed != 'true'
      shell: bash
      run: |
        go install github.com/mikefarah/yq/v4@latest

    - uses: actions/checkout@v4
      with:
        repository: "${{ inputs.repository }}"

    - name: Load environment
      env:
        FILTER: '. | to_entries | map([.key, .value] | join ("=")) | .[]'
        PATH: "${{ inputs.path }}"
      shell: bash
      run: |
        yq "${FILTER}" "${PATH}/env.yml" >> "${GITHUB_ENV}"
