name: 'env'
description: 'Share variables between spaceporn dependencies workflows'
runs:
  using: "composite"
  steps:
    - name: Install yq
      shell: bash
      run: |
        sudo snap install yq

    - name: Load environment
      shell: bash
      run: |
        yq '. | to_entries | map([.key, .value] | join ("=")) | .[]' "${GITHUB_ACTION_PATH}/env.yml" >> "${GITHUB_ENV}"
