name: 'env'
description: 'Share variables between spaceporn dependencies workflows'
runs:
  using: "composite"
  steps:
    - name: Install yq
      shell: ${{ env.shell }}
      run: |
        sudo snap install yq

    - name: Load environment
      shell: ${{ env.shell }}
      run: |
        yq '. | to_entries | map([.key, "\"" + .value + "\""] | join ("=")) | .[]' "${GITHUB_ACTION_PATH}/env.yml" >> "${GITHUB_ENV}"
