name: 'env'
description: 'Share variables between spaceporn dependencies workflows'
runs:
  using: "composite"
  steps:
    - name: Install yq
      shell: ${{ env.shell }}
      run: |
        sudo snap install yq

    - name: Load environment
      shell: ${{ env.shell }}
      run: |
        yq "${{ env.bash_from_yaml }}" "${GITHUB_ACTION_PATH}/env.yml" >> "${GITHUB_ENV}"
