name: 'env'
description: 'Share variables between spaceporn dependencies workflows'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v5

    - name: Install yq
      shell: bash
      run: |
        go install github.com/mikefarah/yq/v4@latest

    - name: Load environment
      shell: bash
      run: |
        yq '. | to_entries | map([.key, .value] | join ("=")) | .[]' "${GITHUB_ACTION_PATH}/env.yml" >> "${GITHUB_ENV}"
