name: cd ping

on:
  push:
    tags:
      - '*'

jobs:
  ping:
    permissions:
      contents: write
    strategy:
      matrix:
        repo:
          - spaceporn-action-bot
          - spaceporn-action-ci
          - spaceporn-action-cd-ping
          - spaceporn-action-cd-pong
          - spaceporn
          - cimgui.zig
    runs-on: ubuntu-latest
    steps:
    - uses: tiawl/spaceporn-action-cd-ping@v1.0.1
      with:
        from: "${{ github.event.repository.name }}"
        is_composite: 'true'
        to: "${{ matrix.repo }}"
        tag: "${{ github.ref_name }}"
        token: "${{ secrets.PAT }}"
