name: cd ping

on:
  push:
    tags:
      - '*'

jobs:
  ping:
    permissions:
      contents: write
    strategy:
      matrix:
        repo:
          - spaceporn-dep-action-bot
          - spaceporn-dep-action-ci
          - spaceporn-dep-action-cd-ping
          - spaceporn-dep-action-cd-pong
          - spaceporn
    runs-on: ubuntu-latest
    steps:
    - uses: tiawl/spaceporn-dep-action-cd-ping@0.0.0
      with:
        repository_name: "${{ github.event.repository.name }}"
        is_composite: 'true'
        user: "${{ matrix.repo }}"
        tag: "${{ github.ref_name }}"
        token: "${{ secrets.PAT }}"
