name: bot

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install yq
      shell: ${{ env.shell }}
      run: |
        sudo snap install yq

    - name: Load environment
      shell: ${{ env.shell }}
      run: |
        yq '. | to_entries | map([.key, .value] | join ("=")) | .[]' "${GITHUB_ACTION_PATH}/env.yml" >> "${GITHUB_ENV}"
        echo "env.my_var='${{ env.my_var }}'"
